# Generated by Django 5.1.1 on 2026-06-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(blank=True, max_length=120, null=True)),
                ('action', models.CharField(max_length=120)),
                ('target', models.CharField(blank=True, max_length=255, null=True)),
                ('safety_mode', models.CharField(default='READ_ONLY', max_length=40)),
                ('status', models.CharField(default='ALLOWED', max_length=40)),
                ('details', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
